### ISSUE TITLE
Cannot listen to leaflet tile layer event listeners

### ISSUE THREAD

**Issue by mo-martinwilson** [andrewgryan/leaflet-html#19]
Pleaes add teh ability to simply access leaflet tile layer events when added or removed from the DOM.

**Comment by andrewgryan** [comment]
Excellent suggestion,

This is possible using the following

```js

const el = document.querySelector("l-map")
el.addEventListener("map:addTo", (ev) => {
   const layer = console.log({ layer: ev.detail })
})
```

But perhaps a better documented and supported public API would be suitable here. Thanks for the suggestion!

**Comment by andrewgryan** [comment]
@mo-martinwilson the proposal is to name events with a prefix `l:` and referencing their leaflet object and the DOM event that triggered them. E.g. `connected`, `disconnected`, `added`, `removed` etc.

That would mean changing the code from `map:addTo` to `l:layer:connected`, a minor change for your use case but will be available in the next version release, e.g. `0.8.0`.

Also, the keys are exported from the `events.js` module, perhaps they should be importable in a `ES module` script? 

```html
<script type="module">
import { layerConnected } from "leaflet-html/events";

// Perhaps?
</script>
```
