### ISSUE TITLE
Replace Microbundle with Vite

### ISSUE THREAD

**Issue by mo-martinwilson** [andrewgryan/leaflet-html#47]
Whilst developing I was playing with Storybook to see if the development experience could be improved for extending/maintaining the library. Storybook for Web Components [requires Vite >= 4.0](https://storybook.js.org/docs/get-started/frameworks/web-components-vite?renderer=web-components). Additionally, [microbundle hasn't been updated for two years](https://www.npmjs.com/package/microbundle), and has 42 dependencies; whilst [Vite has three dependencies](https://www.npmjs.com/package/vite?activeTab=dependencies) and is currently actively maintained. 

Would it be possible to update the build tool from microbundle to Vite?

**Comment by andrewgryan** [comment]
Closed by #49
