### ISSUE TITLE
Code examples in Docs not working

### ISSUE THREAD

**Issue by mo-martinwilson** [andrewgryan/leaflet-html#48]
Using Firefox 131.0.3 (64 bit) on a Windows machine, I am struggling to see the example previews of any code. It would be great if these live code examples were fixed. See image below taken from https://andrewgryan.github.io/leaflet-html/ 

![image](https://github.com/user-attachments/assets/15b80d64-dec4-4789-9113-0fb2c1537cea)

**Comment by andrewgryan** [comment]
Resolved by #47
